### ISSUE TITLE
Remove rosbag dependency in favor of genpy

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/python-mcap-ros1-support#6]
We don't actually need the rosbag dependency, only genpy:

https://github.com/foxglove/jupyter-data-platform/blob/main/Pipfile#L15

We can also drop std_msgs since thats on the end user to install depending on what messages they want to decode.

Is there a way to separate the dependencies we need to run the tests from the dependencies for the package?

**Comment by foxymiles** [comment]
> Is there a way to separate the dependencies we need to run the tests from the dependencies for the package?

Yeah we can move things that we only need to run the tests to the `[dev-packages]` section of the Pipfile.
